# version: 2
# updates:
#   - package-ecosystem: "pip"
#     directory: "/"
#     schedule:
#       interval: "weekly"
#       day: "monday"
#       time: "08:00"
#       timezone: "America/Chicago"
#     open-pull-requests-limit: 3
#     rebase-strategy: "auto"
#     commit-message:
#       prefix: "deps"
#       include: "scope"
